name: Build and Publish Go Packages

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install golang-go
        
    - name: Build submodules
      run: |
        cd liqo
        go build -o liqo .
        cd ../live-migration-operator
        go build -o live-migration-operator .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Build and push Docker images
      run: |
        cd liqo
        docker build -t ${DOCKER_USERNAME}/liqo:latest .
        docker push ${DOCKER_USERNAME}/liqo:latest
        cd ../live-migration-operator
        docker build -t ${DOCKER_USERNAME}/live-migration-operator:latest .
        docker push ${DOCKER_USERNAME}/live-migration-operator:latest
        
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ env.GHCR_TOKEN }}
        
    - name: Publish to GHCR
      run: |
        cd liqo
        echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ env.GHCR_USERNAME }} --password-stdin
        docker tag ${DOCKER_USERNAME}/submodule1:latest ghcr.io/${{ env.GHCR_USERNAME }}/liqo:latest
        docker push ghcr.io/${{ env.GHCR_USERNAME }}/liqo:latest
        cd ../live-migration-operator
        echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ env.GHCR_USERNAME }} --password-stdin
        docker tag ${DOCKER_USERNAME}/submodule2:latest ghcr.io/${{ env.GHCR_USERNAME }}/live-migration-operator:latest
        docker push ghcr.io/${{ env.GHCR_USERNAME }}/live-migration-operator:latest
