name: Build and Publish Go Packages

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install GO enviroment
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'

    - name: Build submodules
      run: |
        cd liqo
        go build -o virtual-kubelet ./cmd/virtual-kubelet
        go build -o liqonet ./cmd/liqonet
        cd ../live-migration-operator
        go build -o live-migration-operator .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
        
    - name: Build and push Docker images
      run: |
        cd liqo
        docker build -t ${DOCKER_USERNAME}/virtual-kubelet:latest .
        docker push ${DOCKER_USERNAME}/virtual-kubelet:latest
        cd ../live-migration-operator
        docker build -t ${DOCKER_USERNAME}/live-migration-operator:latest .
        docker push ${DOCKER_USERNAME}/live-migration-operator:latest
        
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ env.GHCR_TOKEN }}
        
    - name: Publish to GHCR
      run: |
        cd liqo
        echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ env.GHCR_USERNAME }} --password-stdin
        docker tag ${DOCKER_USERNAME}/virtual-kubelet:latest ghcr.io/${{ env.GHCR_USERNAME }}/virtual-kubelet:latest
        docker push ghcr.io/${{ env.GHCR_USERNAME }}/virtual-kubelet:latest
        cd ../live-migration-operator
        echo ${{ env.GHCR_TOKEN }} | docker login ghcr.io -u ${{ env.GHCR_USERNAME }} --password-stdin
        docker tag ${DOCKER_USERNAME}/live-migration-operator:latest ghcr.io/${{ env.GHCR_USERNAME }}/live-migration-operator:latest
        docker push ghcr.io/${{ env.GHCR_USERNAME }}/live-migration-operator:latest
